### ISSUE TITLE
Handling errors during API call

### ISSUE THREAD

**Issue by ramontayag** [shideneyu/kraken_client#11]
There seem to be some instances where the gem blows up because `Hashie::Mash.new` cannot handle the response returned. See [this fork](https://github.com/helloluis/kraken_client/commit/a286007bdc8bb1b2e9176499605b0d0537018372).

Are you aware of this? I don't mind making the change, but is there a test API server for Kraken?

**Comment by shideneyu** [comment]
I was not aware of that, thanks for the report. I shall check this fork commit and shall merge (in a week if I got time) it if it's alright
And no unfortunately there are no test API server for Kraken ~

**Comment by ramontayag** [comment]
Thanks for the quick reply. In that case, I can write a unit test for it. I'll submit a pull request soon. Would you prefer the behaviour in that commit (raise `KrakenClient::ArgumentError`) or something else?

**Comment by shideneyu** [comment]
sure that would be nice, thank you for your contribution. Creating a new exception would be nice (Exception::UnhandledResponse for example)

**Comment by ramontayag** [comment]
Closing this since it's been merged
