### ISSUE TITLE
Status Missing from Kraken Response

### ISSUE THREAD

**Issue by ianschreuder** [shideneyu/kraken_client#19]
Hello,
I'm getting an exception trying to connect to kraken. Looks like your gem is expecting status in the response, but httparty isn't providing that.

> irb
2.2.5 :001 > require 'kraken_client'
2.2.5 :002 > client = KrakenClient.load
 => #<KrakenClient::Application:0x007fdceb085870 @config=#<KrakenClient::Configuration:0x007fdceb084dd0 @api_key=nil, @api_secret=nil, @base_uri="https://api.kraken.com", @api_version=0, @limiter=true, @tier=2, @limiter_interface=#<KrakenClient::Requests::Limiter:0x007fdceb084da8 @config=#<KrakenClient::Configuration:0x007fdceb084dd0 ...>, @previous_timestamps=2017-12-23 10:31:23 -0700, @counter=10, @current_count=10>>>

2.2.5 :003 > time = client.public.server_time
response - {\"error\":[],\"result\":{\"unixtime\":1514050288,\"rfc1123\":\"Sat, 23 Dec 17 17:31:28 +0000\"}}"
Exception - NoMethodError: undefined method `status' for #<HTTParty::Response:0x007fdcec0aa2f0>
	from /Users/ian/.rvm/gems/ruby-2.2.5/gems/httparty-0.15.6/lib/httparty/response.rb:93:in `method_missing'
	from /Users/ian/.rvm/gems/ruby-2.2.5/gems/kraken_client-1.3.0/lib/kraken_client/endpoints/public.rb:9:in `perform'_

**Comment by nicolascochin** [comment]
Hi, 

I faced the same issue. I proposed a PR : https://github.com/shideneyu/kraken_client/pull/18

Regards,

Nico
