### ISSUE TITLE
find: No such file or directory

### ISSUE THREAD

**Issue by thorstenhirsch** [shideneyu/kraken_client#5]
My codeline "require 'kraken_client'" fails:

```
$ ./test.rb 
/Users/torti/.rbenv/versions/2.2.4/lib/ruby/2.2.0/find.rb:42:in `block in find': No such file or directory (Errno::ENOENT)
    from /Users/torti/.rbenv/versions/2.2.4/lib/ruby/2.2.0/find.rb:42:in `collect!'
    from /Users/torti/.rbenv/versions/2.2.4/lib/ruby/2.2.0/find.rb:42:in `find'
    from /Users/torti/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/kraken_client-0.2.1/lib/kraken_client.rb:4:in `each'
    from /Users/torti/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/kraken_client-0.2.1/lib/kraken_client.rb:4:in `select'
    from /Users/torti/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/kraken_client-0.2.1/lib/kraken_client.rb:4:in `<top (required)>'
    from /Users/torti/.rbenv/versions/2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
    from /Users/torti/.rbenv/versions/2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
    from /Users/torti/.rbenv/versions/2.2.4/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    from /Users/torti/src/bc/mytrader/market/kraken.rb:1:in `<top (required)>'
    from /Users/torti/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/require_all-1.3.3/lib/require_all.rb:108:in `require'
    from /Users/torti/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/require_all-1.3.3/lib/require_all.rb:108:in `block in require_all'
    from /Users/torti/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/require_all-1.3.3/lib/require_all.rb:106:in `each'
    from /Users/torti/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/require_all-1.3.3/lib/require_all.rb:106:in `require_all'
    from /Users/torti/src/bc/mytrader/main.rb:9:in `init'
    from ./test.rb:4:in `<main>'
```

So I guess there's a problem with find in your kraken_client.rb produces this issue:

```
Find.find('./lib').select { |p| /.*\.rb$/ =~ p }.each do |path|
  require_relative("../" + path)
end
```

I haven't seen such code in other ruby libraries. They all require their files explicitly, e.g.:

```
require 'configurable.rb'
require 'configuration.rb'
require 'exceptions.rb'
require 'version.rb'
require 'kraken_client/requests/base.rb'
require 'kraken_client/requests/get.rb'
require 'kraken_client/requests/limiter.rb'
require 'kraken_client/requests/post.rb'
require 'kraken_client/application.rb'
```

I don't know if that's all... but at least I don't get an error anymore when I "require 'kraken_client'". That way you also can remove your dependency of the find gem.

**Comment by thorstenhirsch** [comment]
P.S.: My ruby environment is OS X 10.11/homebrew/rbenv/ruby 2.2.4.

**Comment by shideneyu** [comment]
Hello, Thanks you for your report.
I see your point. The purpose of those three lines is to get rid of the necessity of appending a line each time that I will create a new file. It is supposed to works fine.

However, I cannot reproduce your issue. Just installed a fresh version of 2.2.4 using rbenv on Linux Mint 17:

```
➜  ~ ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
➜  ~ gem install kraken_client
Fetching: kraken_client-1.1.3.gem (100%)
Successfully installed kraken_client-1.1.3
Parsing documentation for kraken_client-1.1.3
Installing ri documentation for kraken_client-1.1.3
Done installing documentation for kraken_client after 0 seconds
1 gem installed
➜  ~ irb
rirb(main):001:0> require 'kraken_client'
=> true

```

Do you have the steps with which I can reproduce your issue ? And Thank you for the report.

**Comment by shideneyu** [comment]
Oh, wait, this code does not exist anymore. You are using an older version of kraken_client.

Please use the latest version (1.1.3). You are using version 0.2.1.

So yeah for the information, previously, the "find" was not working, I replaced it by this code :) :

```
ruby_project_files = Dir[File.join(File.dirname(__FILE__), '**', '*.rb')]

ruby_project_files.sort_by!{ |file_name| file_name.downcase }.each do |path|
  require_relative path
end
```

Happy Bot Coding !

**Comment by thorstenhirsch** [comment]
Oh, I did not specify any version in my Gemfile. But yes, a "bundle update"
updates kraken_client to 1.1.3. Uhm... but now I get this error:

$ ./test.rb

/Users/torti/.rbenv/versions/2.2.4/lib/ruby/2.2.0/rubygems/specification.rb:2112:in
`raise_if_conflicts': Unable to activate kraken_client-1.1.3, because
activesupport-4.2.6 conflicts with activesupport (~> 3.2)
(Gem::ConflictError)

I also use some activesupport stuff in my application, so 4.2.6 is already
installed. Do you really need version "~> 3.2" of activesupport? Yesterday
it looked like 4.2.6 is just as fine.

Thorsten

2016-04-05 10:21 GMT+02:00 Shideneyu notifications@github.com:

**Comment by shideneyu** [comment]
Please use [Bundler](http://bundler.io/). You are creating some hacks to get it working, but this is not the right way to do (and not related to kraken_client).

Once you create a `gemfile` and delegate the dependancies requirement there, you will be able to use both version. Right now your code is obstrusive, that is why you are encountering [this issue.](http://stackoverflow.com/a/22580691/1468585)

[Edit]: Oh wait, you are already using it ? What does a `bundle install` does then ?

**Comment by thorstenhirsch** [comment]
Oh, right, I had installed activesupport 4.2.6 directly with "gem install".
After removing that version everything's fine now ...well, as long as I
don't rely on a newer version of activesupport than 3.2. Of course both
versions can be installed simultaneously, but they can't be loaded at
runtime simultaneously. Let's say I need a feature that came with 4.2 and
specify that version in my Gemfile, bundler will upgrade activesupport and
downgrade kraken_client:

$ bundle update

[...]

Using httparty 0.13.7

Installing activesupport 4.2.6 (was 3.2.22.2)

[...]

Installing kraken_client 0.2.1 (was 1.1.3)

Using http-cookie 1.0.2

[...]

So my suggestion still is - as long as there's no incompatible change in a
more recent version - that kraken_client should not depend on activesupport
3.2. Maybe ">= 3.2" would be a better fit.

Whatever you think about my idea - thank you for you support!

Cheers!
Thorsten

2016-04-05 11:14 GMT+02:00 Shideneyu notifications@github.com:

**Comment by shideneyu** [comment]
My pleasure :) ! Happy to have helped you. Good luck for your project !

**Comment by shideneyu** [comment]
I'll upgrade it as per your suggestion, it is actually a good one
