### ISSUE TITLE
OHLC data endpoint not supported

### ISSUE THREAD

**Issue by thibauld** [shideneyu/kraken_client#9]
I was surprised to see that kraken OHLC api endpoint was not supported:
https://www.kraken.com/help/api#public-market-data
It would be great to add the endpoint to kraken_client
thanks

**Comment by tlight** [comment]
came to say the same thing, great client thanks for the work!

**Comment by shideneyu** [comment]
Hello ! Thank you for your report and support, I will implement it when I can :)

**Comment by shideneyu** [comment]
Implemented thanks to elliottbernstein ( https://github.com/shideneyu/kraken_client/pull/14 )

I am closing this ticket
